manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-hid-io
      remote: badjeff
      #revision: main
    - name: zmk-analog-input-driver
      remote: badjeff
      #revision: main
